// 외래키 연결 엣지들
// export const initialEdges: Edge[] = [
//   {
//     id: "posts-user",
//     source: "posts",
//     target: "users",
//     sourceHandle: "source-user_id",
//     targetHandle: "target-id",
//     type: "smoothstep",
//     animated: true,
//     style: { stroke: getRandomColor(), strokeWidth: 2 },
//     labelStyle: { fill: "#0ea5e9", fontWeight: "bold", fontSize: 12 },
//   },
//   {
//     id: "comments-user",
//     source: "comments",
//     target: "users",
//     sourceHandle: "source-user_id",
//     targetHandle: "target-id",
//     type: "smoothstep",
//     animated: true,
//     style: { stroke: getRandomColor(), strokeWidth: 2 },
//     labelStyle: { fill: "#10b981", fontWeight: "bold", fontSize: 12 },
//   },
//   {
//     id: "comments-post",
//     source: "comments",
//     target: "posts",
//     sourceHandle: "source-post_id",
//     targetHandle: "target-id",
//     type: "smoothstep",
//     animated: true,
//     style: { stroke: getRandomColor(), strokeWidth: 2 },
//     labelStyle: { fill: "#f59e0b", fontWeight: "bold", fontSize: 12 },
//   },
//   {
//     id: "post-categories-post",
//     source: "post_categories",
//     target: "posts",
//     sourceHandle: "source-post_id",
//     targetHandle: "target-id",
//     type: "smoothstep",
//     animated: true,
//     style: { stroke: getRandomColor(), strokeWidth: 2 },
//     labelStyle: { fill: "#8b5cf6", fontWeight: "bold", fontSize: 12 },
//   },
//   {
//     id: "post-categories-category",
//     source: "post_categories",
//     target: "categories",
//     sourceHandle: "source-category_id",
//     targetHandle: "target-id",
//     type: "smoothstep",
//     animated: true,
//     style: { stroke: getRandomColor(), strokeWidth: 2 },
//     labelStyle: { fill: "#ec4899", fontWeight: "bold", fontSize: 12 },
//   },
//   {
//     id: "comments-post",
//     source: "comments",
//     target: "posts",
//     sourceHandle: "source-post_id",
//     targetHandle: "target-id",
//     type: "smoothstep",
//     animated: true,
//     label: "1 : N",
//     style: { stroke: getRandomColor(), strokeWidth: 2 },
//     labelStyle: { fill: "#f59e0b", fontWeight: "bold", fontSize: 12 },
//   },
//   {
//     id: "post-categories-post",
//     source: "post_categories",
//     target: "posts",
//     sourceHandle: "source-post_id",
//     targetHandle: "target-id",
//     type: "smoothstep",
//     animated: true,
//     label: "N : M",
//     style: { stroke: getRandomColor(), strokeWidth: 2 },
//     labelStyle: { fill: "#8b5cf6", fontWeight: "bold", fontSize: 12 },
//   },
//   {
//     id: "post-categories-category",
//     source: "post_categories",
//     target: "categories",
//     sourceHandle: "source-category_id",
//     targetHandle: "target-id",
//     type: "smoothstep",
//     animated: true,
//     label: "N : M",
//     style: { stroke: getRandomColor(), strokeWidth: 2 },
//     labelStyle: { fill: "#ec4899", fontWeight: "bold", fontSize: 12 },
//   },
// ];
